/* Generated by ldk. Do not edit -- `ldk stubs virtio-net` rewrites this file.
 *
 * One stub for every symbol virtio-net asks the kernel for and nk does not yet
 * provide. Each one panics rather than returning a plausible value, because
 * a stub that quietly returns 0 is a driver that appears to work and does
 * something subtly wrong instead -- which is far harder to find than a halt
 * naming the function.
 *
 * This file is committed on purpose. It is the record of what the shim owes
 * this driver, and its diff is the clearest possible statement of what a new
 * driver cost.
 *
 * Implement one by writing it in ../emul/ and re-running `ldk stubs virtio-net`;
 * anything the shim defines drops out of here automatically.
 */

void nk_stub_called(const char *name);

/* @stub __bitmap_complement */
long __bitmap_complement(void);
long __bitmap_complement(void) { nk_stub_called("__bitmap_complement"); return 0; }

/* @stub __bitmap_weight */
long __bitmap_weight(void);
long __bitmap_weight(void) { nk_stub_called("__bitmap_weight"); return 0; }

/* @stub __clk_get_name */
long __clk_get_name(void);
long __clk_get_name(void) { nk_stub_called("__clk_get_name"); return 0; }

/* @stub __dev_fwnode */
long __dev_fwnode(void);
long __dev_fwnode(void) { nk_stub_called("__dev_fwnode"); return 0; }

/* @stub __get_random_u32_below */
long __get_random_u32_below(void);
long __get_random_u32_below(void) { nk_stub_called("__get_random_u32_below"); return 0; }

/* @stub __skb_flow_dissect */
long __skb_flow_dissect(void);
long __skb_flow_dissect(void) { nk_stub_called("__skb_flow_dissect"); return 0; }

/* @stub __skb_get_poff */
long __skb_get_poff(void);
long __skb_get_poff(void) { nk_stub_called("__skb_get_poff"); return 0; }

/* @stub __sw_hweight64 */
long __sw_hweight64(void);
long __sw_hweight64(void) { nk_stub_called("__sw_hweight64"); return 0; }

/* @stub _parse_integer_fixup_radix */
long _parse_integer_fixup_radix(void);
long _parse_integer_fixup_radix(void) { nk_stub_called("_parse_integer_fixup_radix"); return 0; }

/* @stub _parse_integer_limit */
long _parse_integer_limit(void);
long _parse_integer_limit(void) { nk_stub_called("_parse_integer_limit"); return 0; }

/* @stub alt_cb_patch_nops */
static long stub_alt_cb_patch_nops(void) { nk_stub_called("alt_cb_patch_nops"); return 0; }
void *alt_cb_patch_nops = (void *)stub_alt_cb_patch_nops;

/* @stub bpf_dispatcher_xdp_func */
long bpf_dispatcher_xdp_func(void);
long bpf_dispatcher_xdp_func(void) { nk_stub_called("bpf_dispatcher_xdp_func"); return 0; }

/* @stub bpf_master_redirect_enabled_key */
static long stub_bpf_master_redirect_enabled_key(void) { nk_stub_called("bpf_master_redirect_enabled_key"); return 0; }
void *bpf_master_redirect_enabled_key = (void *)stub_bpf_master_redirect_enabled_key;

/* @stub bpf_prog_add */
long bpf_prog_add(void);
long bpf_prog_add(void) { nk_stub_called("bpf_prog_add"); return 0; }

/* @stub bpf_prog_put */
long bpf_prog_put(void);
long bpf_prog_put(void) { nk_stub_called("bpf_prog_put"); return 0; }

/* @stub bpf_prog_sub */
long bpf_prog_sub(void);
long bpf_prog_sub(void) { nk_stub_called("bpf_prog_sub"); return 0; }

/* @stub bpf_stats_enabled_key */
static long stub_bpf_stats_enabled_key(void) { nk_stub_called("bpf_stats_enabled_key"); return 0; }
void *bpf_stats_enabled_key = (void *)stub_bpf_stats_enabled_key;

/* @stub bpf_warn_invalid_xdp_action */
long bpf_warn_invalid_xdp_action(void);
long bpf_warn_invalid_xdp_action(void) { nk_stub_called("bpf_warn_invalid_xdp_action"); return 0; }

/* @stub cancel_work_sync */
long cancel_work_sync(void);
long cancel_work_sync(void) { nk_stub_called("cancel_work_sync"); return 0; }

/* @stub csum_partial */
long csum_partial(void);
long csum_partial(void) { nk_stub_called("csum_partial"); return 0; }

/* @stub do_trace_netlink_extack */
long do_trace_netlink_extack(void);
long do_trace_netlink_extack(void) { nk_stub_called("do_trace_netlink_extack"); return 0; }

/* @stub dst_release */
long dst_release(void);
long dst_release(void) { nk_stub_called("dst_release"); return 0; }

/* @stub errname */
long errname(void);
long errname(void) { nk_stub_called("errname"); return 0; }

/* @stub flow_keys_basic_dissector */
static long stub_flow_keys_basic_dissector(void) { nk_stub_called("flow_keys_basic_dissector"); return 0; }
void *flow_keys_basic_dissector = (void *)stub_flow_keys_basic_dissector;

/* @stub fwnode_count_parents */
long fwnode_count_parents(void);
long fwnode_count_parents(void) { nk_stub_called("fwnode_count_parents"); return 0; }

/* @stub fwnode_get_name */
long fwnode_get_name(void);
long fwnode_get_name(void) { nk_stub_called("fwnode_get_name"); return 0; }

/* @stub fwnode_get_name_prefix */
long fwnode_get_name_prefix(void);
long fwnode_get_name_prefix(void) { nk_stub_called("fwnode_get_name_prefix"); return 0; }

/* @stub fwnode_get_nth_parent */
long fwnode_get_nth_parent(void);
long fwnode_get_nth_parent(void) { nk_stub_called("fwnode_get_nth_parent"); return 0; }

/* @stub fwnode_property_read_u8_array */
long fwnode_property_read_u8_array(void);
long fwnode_property_read_u8_array(void) { nk_stub_called("fwnode_property_read_u8_array"); return 0; }

/* @stub gfpflag_names */
static long stub_gfpflag_names(void) { nk_stub_called("gfpflag_names"); return 0; }
void *gfpflag_names = (void *)stub_gfpflag_names;

/* @stub gro_find_complete_by_type */
long gro_find_complete_by_type(void);
long gro_find_complete_by_type(void) { nk_stub_called("gro_find_complete_by_type"); return 0; }

/* @stub gro_find_receive_by_type */
long gro_find_receive_by_type(void);
long gro_find_receive_by_type(void) { nk_stub_called("gro_find_receive_by_type"); return 0; }

/* @stub guid_index */
static long stub_guid_index(void) { nk_stub_called("guid_index"); return 0; }
void *guid_index = (void *)stub_guid_index;

/* @stub has_capability_noaudit */
long has_capability_noaudit(void);
long has_capability_noaudit(void) { nk_stub_called("has_capability_noaudit"); return 0; }

/* @stub iov_iter_advance */
long iov_iter_advance(void);
long iov_iter_advance(void) { nk_stub_called("iov_iter_advance"); return 0; }

/* @stub iov_iter_extract_pages */
long iov_iter_extract_pages(void);
long iov_iter_extract_pages(void) { nk_stub_called("iov_iter_extract_pages"); return 0; }

/* @stub is_vmalloc_or_module_addr */
long is_vmalloc_or_module_addr(void);
long is_vmalloc_or_module_addr(void) { nk_stub_called("is_vmalloc_or_module_addr"); return 0; }

/* @stub net_dim_get_rx_irq_moder */
long net_dim_get_rx_irq_moder(void);
long net_dim_get_rx_irq_moder(void) { nk_stub_called("net_dim_get_rx_irq_moder"); return 0; }

/* @stub net_dim_setting */
long net_dim_setting(void);
long net_dim_setting(void) { nk_stub_called("net_dim_setting"); return 0; }

/* @stub net_failover_create */
long net_failover_create(void);
long net_failover_create(void) { nk_stub_called("net_failover_create"); return 0; }

/* @stub net_failover_destroy */
long net_failover_destroy(void);
long net_failover_destroy(void) { nk_stub_called("net_failover_destroy"); return 0; }

/* @stub nf_conntrack_destroy */
long nf_conntrack_destroy(void);
long nf_conntrack_destroy(void) { nk_stub_called("nf_conntrack_destroy"); return 0; }

/* @stub nvmem_cell_get */
long nvmem_cell_get(void);
long nvmem_cell_get(void) { nk_stub_called("nvmem_cell_get"); return 0; }

/* @stub nvmem_cell_put */
long nvmem_cell_put(void);
long nvmem_cell_put(void) { nk_stub_called("nvmem_cell_put"); return 0; }

/* @stub nvmem_cell_read */
long nvmem_cell_read(void);
long nvmem_cell_read(void) { nk_stub_called("nvmem_cell_read"); return 0; }

/* @stub of_find_property */
long of_find_property(void);
long of_find_property(void) { nk_stub_called("of_find_property"); return 0; }

/* @stub of_get_mac_address */
long of_get_mac_address(void);
long of_get_mac_address(void) { nk_stub_called("of_get_mac_address"); return 0; }

/* @stub of_prop_next_string */
long of_prop_next_string(void);
long of_prop_next_string(void) { nk_stub_called("of_prop_next_string"); return 0; }

/* @stub of_property_read_string */
long of_property_read_string(void);
long of_property_read_string(void) { nk_stub_called("of_property_read_string"); return 0; }

/* @stub pageflag_names */
static long stub_pageflag_names(void) { nk_stub_called("pageflag_names"); return 0; }
void *pageflag_names = (void *)stub_pageflag_names;

/* @stub panic */
long panic(void);
long panic(void) { nk_stub_called("panic"); return 0; }

/* @stub param_ops_bool */
static long stub_param_ops_bool(void) { nk_stub_called("param_ops_bool"); return 0; }
void *param_ops_bool = (void *)stub_param_ops_bool;

/* @stub param_ops_int */
static long stub_param_ops_int(void) { nk_stub_called("param_ops_int"); return 0; }
void *param_ops_int = (void *)stub_param_ops_int;

/* @stub siphash_1u64 */
long siphash_1u64(void);
long siphash_1u64(void) { nk_stub_called("siphash_1u64"); return 0; }

/* @stub sized_strscpy */
long sized_strscpy(void);
long sized_strscpy(void) { nk_stub_called("sized_strscpy"); return 0; }

/* @stub skb_coalesce_rx_frag */
long skb_coalesce_rx_frag(void);
long skb_coalesce_rx_frag(void) { nk_stub_called("skb_coalesce_rx_frag"); return 0; }

/* @stub skb_copy_bits */
long skb_copy_bits(void);
long skb_copy_bits(void) { nk_stub_called("skb_copy_bits"); return 0; }

/* @stub skb_tstamp_tx */
long skb_tstamp_tx(void);
long skb_tstamp_tx(void) { nk_stub_called("skb_tstamp_tx"); return 0; }

/* @stub skip_spaces */
long skip_spaces(void);
long skip_spaces(void) { nk_stub_called("skip_spaces"); return 0; }

/* @stub softnet_data */
static long stub_softnet_data(void) { nk_stub_called("softnet_data"); return 0; }
void *softnet_data = (void *)stub_softnet_data;

/* @stub sprint_backtrace */
long sprint_backtrace(void);
long sprint_backtrace(void) { nk_stub_called("sprint_backtrace"); return 0; }

/* @stub sprint_backtrace_build_id */
long sprint_backtrace_build_id(void);
long sprint_backtrace_build_id(void) { nk_stub_called("sprint_backtrace_build_id"); return 0; }

/* @stub sprint_symbol */
long sprint_symbol(void);
long sprint_symbol(void) { nk_stub_called("sprint_symbol"); return 0; }

/* @stub sprint_symbol_build_id */
long sprint_symbol_build_id(void);
long sprint_symbol_build_id(void) { nk_stub_called("sprint_symbol_build_id"); return 0; }

/* @stub sprint_symbol_no_offset */
long sprint_symbol_no_offset(void);
long sprint_symbol_no_offset(void) { nk_stub_called("sprint_symbol_no_offset"); return 0; }

/* @stub strchrnul */
long strchrnul(void);
long strchrnul(void) { nk_stub_called("strchrnul"); return 0; }

/* @stub string_escape_mem */
long string_escape_mem(void);
long string_escape_mem(void) { nk_stub_called("string_escape_mem"); return 0; }

/* @stub time64_to_tm */
long time64_to_tm(void);
long time64_to_tm(void) { nk_stub_called("time64_to_tm"); return 0; }

/* @stub unpin_user_page */
long unpin_user_page(void);
long unpin_user_page(void) { nk_stub_called("unpin_user_page"); return 0; }

/* @stub uuid_index */
static long stub_uuid_index(void) { nk_stub_called("uuid_index"); return 0; }
void *uuid_index = (void *)stub_uuid_index;

/* @stub vmaflag_names */
static long stub_vmaflag_names(void) { nk_stub_called("vmaflag_names"); return 0; }
void *vmaflag_names = (void *)stub_vmaflag_names;

/* @stub vmalloc_to_page */
long vmalloc_to_page(void);
long vmalloc_to_page(void) { nk_stub_called("vmalloc_to_page"); return 0; }

/* @stub xas_find */
long xas_find(void);
long xas_find(void) { nk_stub_called("xas_find"); return 0; }

/* @stub xdp_convert_zc_to_xdp_frame */
long xdp_convert_zc_to_xdp_frame(void);
long xdp_convert_zc_to_xdp_frame(void) { nk_stub_called("xdp_convert_zc_to_xdp_frame"); return 0; }

/* @stub xdp_do_redirect */
long xdp_do_redirect(void);
long xdp_do_redirect(void) { nk_stub_called("xdp_do_redirect"); return 0; }

/* @stub xdp_features_clear_redirect_target */
long xdp_features_clear_redirect_target(void);
long xdp_features_clear_redirect_target(void) { nk_stub_called("xdp_features_clear_redirect_target"); return 0; }

/* @stub xdp_features_set_redirect_target */
long xdp_features_set_redirect_target(void);
long xdp_features_set_redirect_target(void) { nk_stub_called("xdp_features_set_redirect_target"); return 0; }

/* @stub xdp_master_redirect */
long xdp_master_redirect(void);
long xdp_master_redirect(void) { nk_stub_called("xdp_master_redirect"); return 0; }
