/* Generated by ldk. Do not edit -- `ldk stubs virtio-blk` rewrites this file.
 *
 * One stub for every symbol virtio-blk asks the kernel for and nk does not yet
 * provide. Each one panics rather than returning a plausible value, because
 * a stub that quietly returns 0 is a driver that appears to work and does
 * something subtly wrong instead -- which is far harder to find than a halt
 * naming the function.
 *
 * This file is committed on purpose. It is the record of what the shim owes
 * this driver, and its diff is the clearest possible statement of what a new
 * driver cost.
 *
 * Implement one by writing it in ../emul/ and re-running `ldk stubs virtio-blk`;
 * anything the shim defines drops out of here automatically.
 */

void nk_stub_called(const char *name);

/* @stub __bitmap_complement */
long __bitmap_complement(void);
long __bitmap_complement(void) { nk_stub_called("__bitmap_complement"); return 0; }

/* @stub __clk_get_name */
long __clk_get_name(void);
long __clk_get_name(void) { nk_stub_called("__clk_get_name"); return 0; }

/* @stub _ctype */
static long stub__ctype(void) { nk_stub_called("_ctype"); return 0; }
void *_ctype = (void *)stub__ctype;

/* @stub _find_next_bit */
long _find_next_bit(void);
long _find_next_bit(void) { nk_stub_called("_find_next_bit"); return 0; }

/* @stub _find_next_zero_bit */
long _find_next_zero_bit(void);
long _find_next_zero_bit(void) { nk_stub_called("_find_next_zero_bit"); return 0; }

/* @stub _parse_integer_fixup_radix */
long _parse_integer_fixup_radix(void);
long _parse_integer_fixup_radix(void) { nk_stub_called("_parse_integer_fixup_radix"); return 0; }

/* @stub _parse_integer_limit */
long _parse_integer_limit(void);
long _parse_integer_limit(void) { nk_stub_called("_parse_integer_limit"); return 0; }

/* @stub alt_cb_patch_nops */
static long stub_alt_cb_patch_nops(void) { nk_stub_called("alt_cb_patch_nops"); return 0; }
void *alt_cb_patch_nops = (void *)stub_alt_cb_patch_nops;

/* @stub errname */
long errname(void);
long errname(void) { nk_stub_called("errname"); return 0; }

/* @stub eth_type_trans */
long eth_type_trans(void);
long eth_type_trans(void) { nk_stub_called("eth_type_trans"); return 0; }

/* @stub fwnode_count_parents */
long fwnode_count_parents(void);
long fwnode_count_parents(void) { nk_stub_called("fwnode_count_parents"); return 0; }

/* @stub fwnode_get_name */
long fwnode_get_name(void);
long fwnode_get_name(void) { nk_stub_called("fwnode_get_name"); return 0; }

/* @stub fwnode_get_name_prefix */
long fwnode_get_name_prefix(void);
long fwnode_get_name_prefix(void) { nk_stub_called("fwnode_get_name_prefix"); return 0; }

/* @stub fwnode_get_nth_parent */
long fwnode_get_nth_parent(void);
long fwnode_get_nth_parent(void) { nk_stub_called("fwnode_get_nth_parent"); return 0; }

/* @stub gfpflag_names */
static long stub_gfpflag_names(void) { nk_stub_called("gfpflag_names"); return 0; }
void *gfpflag_names = (void *)stub_gfpflag_names;

/* @stub guid_index */
static long stub_guid_index(void) { nk_stub_called("guid_index"); return 0; }
void *guid_index = (void *)stub_guid_index;

/* @stub has_capability_noaudit */
long has_capability_noaudit(void);
long has_capability_noaudit(void) { nk_stub_called("has_capability_noaudit"); return 0; }

/* @stub iov_iter_advance */
long iov_iter_advance(void);
long iov_iter_advance(void) { nk_stub_called("iov_iter_advance"); return 0; }

/* @stub iov_iter_extract_pages */
long iov_iter_extract_pages(void);
long iov_iter_extract_pages(void) { nk_stub_called("iov_iter_extract_pages"); return 0; }

/* @stub is_vmalloc_or_module_addr */
long is_vmalloc_or_module_addr(void);
long is_vmalloc_or_module_addr(void) { nk_stub_called("is_vmalloc_or_module_addr"); return 0; }

/* @stub of_find_property */
long of_find_property(void);
long of_find_property(void) { nk_stub_called("of_find_property"); return 0; }

/* @stub of_prop_next_string */
long of_prop_next_string(void);
long of_prop_next_string(void) { nk_stub_called("of_prop_next_string"); return 0; }

/* @stub of_property_read_string */
long of_property_read_string(void);
long of_property_read_string(void) { nk_stub_called("of_property_read_string"); return 0; }

/* @stub pageflag_names */
static long stub_pageflag_names(void) { nk_stub_called("pageflag_names"); return 0; }
void *pageflag_names = (void *)stub_pageflag_names;

/* @stub panic */
long panic(void);
long panic(void) { nk_stub_called("panic"); return 0; }

/* @stub siphash_1u64 */
long siphash_1u64(void);
long siphash_1u64(void) { nk_stub_called("siphash_1u64"); return 0; }

/* @stub skip_spaces */
long skip_spaces(void);
long skip_spaces(void) { nk_stub_called("skip_spaces"); return 0; }

/* @stub sprint_backtrace */
long sprint_backtrace(void);
long sprint_backtrace(void) { nk_stub_called("sprint_backtrace"); return 0; }

/* @stub sprint_backtrace_build_id */
long sprint_backtrace_build_id(void);
long sprint_backtrace_build_id(void) { nk_stub_called("sprint_backtrace_build_id"); return 0; }

/* @stub sprint_symbol */
long sprint_symbol(void);
long sprint_symbol(void) { nk_stub_called("sprint_symbol"); return 0; }

/* @stub sprint_symbol_build_id */
long sprint_symbol_build_id(void);
long sprint_symbol_build_id(void) { nk_stub_called("sprint_symbol_build_id"); return 0; }

/* @stub sprint_symbol_no_offset */
long sprint_symbol_no_offset(void);
long sprint_symbol_no_offset(void) { nk_stub_called("sprint_symbol_no_offset"); return 0; }

/* @stub strchrnul */
long strchrnul(void);
long strchrnul(void) { nk_stub_called("strchrnul"); return 0; }

/* @stub string_escape_mem */
long string_escape_mem(void);
long string_escape_mem(void) { nk_stub_called("string_escape_mem"); return 0; }

/* @stub time64_to_tm */
long time64_to_tm(void);
long time64_to_tm(void) { nk_stub_called("time64_to_tm"); return 0; }

/* @stub unpin_user_page */
long unpin_user_page(void);
long unpin_user_page(void) { nk_stub_called("unpin_user_page"); return 0; }

/* @stub uuid_index */
static long stub_uuid_index(void) { nk_stub_called("uuid_index"); return 0; }
void *uuid_index = (void *)stub_uuid_index;

/* @stub vmaflag_names */
static long stub_vmaflag_names(void) { nk_stub_called("vmaflag_names"); return 0; }
void *vmaflag_names = (void *)stub_vmaflag_names;

/* @stub vmalloc_to_page */
long vmalloc_to_page(void);
long vmalloc_to_page(void) { nk_stub_called("vmalloc_to_page"); return 0; }

/* @stub xas_find */
long xas_find(void);
long xas_find(void) { nk_stub_called("xas_find"); return 0; }
